import { jsPDF } from "jspdf";

function getSeverity(riskScore) {
  if (riskScore >= 81) return "Critical";
  if (riskScore >= 61) return "High";
  if (riskScore >= 31) return "Medium";
  return "Low";
}

function getRecommendation(prediction) {
  const pred = prediction.toLowerCase();

  if (pred.includes("phish")) {
    return [
      "Block this URL immediately.",
      "Warn the user.",
      "Investigate possible credential compromise.",
      "Add domain to blacklist."
    ];
  }

  return [
    "No immediate action required.",
    "Continue monitoring."
  ];
}

export default function generatePdfReport(scan) {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  // Colors
  const PURPLE = [101, 41, 238];
  const RED = [239, 68, 68];
  const GREEN = [34, 197, 94];
  const BLACK = [0, 0, 0];
  const GRAY = [80, 80, 80];

  const isPhishing = scan.prediction.toLowerCase().includes("phish");
  const severity = getSeverity(scan.risk_score);
  const recommendations = getRecommendation(scan.prediction);

  // Background
  doc.setFillColor(...BLACK);
  doc.rect(0, 0, pageWidth, 297, "F");

  // Header
  doc.setTextColor(...PURPLE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("PHISHGUARD", 20, 20);

  doc.setFontSize(16);
  doc.text("Threat Intelligence Report", 20, 30);

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 38);

  // Divider
  doc.setDrawColor(...PURPLE);
  doc.line(20, 42, 190, 42);

  // Executive Summary
  doc.setTextColor(...PURPLE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Executive Summary", 20, 55);

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const summaryLines = [
    `Risk Score: ${scan.risk_score}%`,
    `Severity: ${severity}`,
    `Timestamp: ${scan.timestamp}`
  ];

  let y = 65;
  summaryLines.forEach((line) => {
    const wrapped = doc.splitTextToSize(line, 170);
    doc.text(wrapped, 20, y);
    y += wrapped.length * 6;
  });

  // Risk Score Highlight
  y += 5;
  doc.setTextColor(...(isPhishing ? RED : GREEN));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(`Risk Score: ${scan.risk_score}%`, 20, y);

  // Detection Reasons
  y += 15;
  doc.setTextColor(...PURPLE);
  doc.setFontSize(14);
  doc.text("Detection Reasons", 20, y);

  y += 10;
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const reasons = scan.reasons?.length
    ? scan.reasons
    : ["No major phishing indicators detected."];

  reasons.forEach((reason) => {
    const wrapped = doc.splitTextToSize(`• ${reason}`, 170);
    doc.text(wrapped, 25, y);
    y += wrapped.length * 6;
  });

  // Recommendations
  y += 8;
  doc.setTextColor(...PURPLE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Recommended Actions", 20, y);

  y += 10;
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  recommendations.forEach((item) => {
    const wrapped = doc.splitTextToSize(`• ${item}`, 170);
    doc.text(wrapped, 25, y);
    y += wrapped.length * 6;
  });

  // Footer
  doc.setTextColor(...GRAY);
  doc.setFontSize(9);
  doc.text(
    "Generated by PhishGuard – AI-Powered Phishing Detection Platform",
    20,
    285
  );

  // Save
  const filename = `PhishGuard_Report_${Date.now()}.pdf`;
  doc.save(filename);
}